### ISSUE TITLE
Problem with display of right to left language

### ISSUE THREAD

**Issue by MinaRashad** [Voklen/Daily-Diary#15]
When I write an arabic text with an english word it is written incorrectly

![Screenshot_20230503_130941](https://user-images.githubusercontent.com/39602891/235990382-90b145d4-d6ff-4ca6-bec0-d178a1b4ac86.jpg)

This is the expected behaviour (samsung notes)
![Screenshot_20230503_133453_Samsung Notes](https://user-images.githubusercontent.com/39602891/235998859-35822784-2c79-4c39-bff2-35b4602af798.jpg)

**Comment by Voklen** [comment]
Ahh yes, I have noticed the framework this app is built on (Flutter) has some really wacky interactions with Arabic text. I previously hadn't got round to investigating but I see what you're saying.

<img src="https://user-images.githubusercontent.com/56766748/236353346-4fcbdb2d-d610-4357-b5fd-4123b05abc08.png" alt="Screenshot with broken Arabic text" width="300">

Flutter has all sorts of odd cursor movements with mixed text but I think this issue https://github.com/flutter/flutter/issues/79749 should hopefully solve the core of the problem. There's not been any activity on it since 2021 so I might have a shot at it when I have time. At the moment there's not much that can be done within the app specifically unfortunately as this is to do with Flutter and not the specific app code.

**Comment by MinaRashad** [comment]
haha, It means "Firstly" in Egyptian Dialect.
but anyway thanks for investigating it

is it possible to create within the app a way to maybe check the first character for each line to decide the alignment? (i.e like every line has its own alignment).

**Comment by Voklen** [comment]
Ahhh interesting, thank you

Unfortunately there's no way to change the text direction per line. _Technically_ it might be possible to have a new `TextField` on every line but that would mean I'd have to implement enter cursor movement myself (which I don't know if it's even possible with Flutter) and would need a lot of string appending and splitting every time the app opens or saves a file. At that point I may as well contribute to Flutter for an actual solution.
